name: Deploy Bot

on:
  push:
    branches:
      - main  # Change this to your preferred branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Cancel previous deployment
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
        workflow_file: bot.yml

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # Replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Install python telegram bot
      run: pip install python-telegram-bot==13.7

    - name: Deploy bot
      run: python bot.py
      env:
        TOKEN: ${{ secrets.TOKEN }}  # Replace with your actual bot token secret name
